// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5FJS9oBbEz3h612TjcIs651uA90JT-KY',
    appId: '1:302537303182:web:a302756a28c151023c15df',
    messagingSenderId: '302537303182',
    projectId: 'heris-7963d',
    authDomain: 'heris-7963d.firebaseapp.com',
    storageBucket: 'heris-7963d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcgl-ti7kNcnNhOD4UuuwtE8AyPLpNIgo',
    appId: '1:302537303182:android:065ab290da9631d73c15df',
    messagingSenderId: '302537303182',
    projectId: 'heris-7963d',
    storageBucket: 'heris-7963d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi-tQBF-05iVF_TfVisiGuajj11SuK3KY',
    appId: '1:302537303182:ios:930122c475a396853c15df',
    messagingSenderId: '302537303182',
    projectId: 'heris-7963d',
    storageBucket: 'heris-7963d.firebasestorage.app',
    iosBundleId: 'com.example.loginpage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi-tQBF-05iVF_TfVisiGuajj11SuK3KY',
    appId: '1:302537303182:ios:930122c475a396853c15df',
    messagingSenderId: '302537303182',
    projectId: 'heris-7963d',
    storageBucket: 'heris-7963d.firebasestorage.app',
    iosBundleId: 'com.example.loginpage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5FJS9oBbEz3h612TjcIs651uA90JT-KY',
    appId: '1:302537303182:web:4b64b7c6a825d5f83c15df',
    messagingSenderId: '302537303182',
    projectId: 'heris-7963d',
    authDomain: 'heris-7963d.firebaseapp.com',
    storageBucket: 'heris-7963d.firebasestorage.app',
  );
}
